language: python

sudo: false

python:
   - "3.5"
   - "3.6"


install:
  - "./travis.sh"


script: 
  - pytest

notifications:
  email:
    on_success:      change
    on_failure:      change

cache: pip